package com.nulljosh.roost

// Ported from src/lib/market.js. Static tables; swap for a live index when there's a real feed.

private val CURRENCIES: Map<String, String> = mapOf(
    "US" to "USD",
    "CA" to "CAD",
    "MX" to "MXN",
    "BR" to "BRL",
    "AR" to "ARS",
    "CL" to "CLP",
    "CO" to "COP",
    "PE" to "PEN",
    "GB" to "GBP",
    "IE" to "EUR",
    "FR" to "EUR",
    "DE" to "EUR",
    "ES" to "EUR",
    "PT" to "EUR",
    "IT" to "EUR",
    "NL" to "EUR",
    "BE" to "EUR",
    "AT" to "EUR",
    "GR" to "EUR",
    "FI" to "EUR",
    "EE" to "EUR",
    "LV" to "EUR",
    "LT" to "EUR",
    "SK" to "EUR",
    "SI" to "EUR",
    "HR" to "EUR",
    "CY" to "EUR",
    "MT" to "EUR",
    "LU" to "EUR",
    "CH" to "CHF",
    "NO" to "NOK",
    "SE" to "SEK",
    "DK" to "DKK",
    "IS" to "ISK",
    "PL" to "PLN",
    "CZ" to "CZK",
    "HU" to "HUF",
    "RO" to "RON",
    "BG" to "BGN",
    "RS" to "RSD",
    "UA" to "UAH",
    "RU" to "RUB",
    "TR" to "TRY",
    "AE" to "AED",
    "SA" to "SAR",
    "QA" to "QAR",
    "KW" to "KWD",
    "BH" to "BHD",
    "OM" to "OMR",
    "IL" to "ILS",
    "JO" to "JOD",
    "EG" to "EGP",
    "MA" to "MAD",
    "TN" to "TND",
    "ZA" to "ZAR",
    "NG" to "NGN",
    "KE" to "KES",
    "GH" to "GHS",
    "TZ" to "TZS",
    "IN" to "INR",
    "PK" to "PKR",
    "BD" to "BDT",
    "LK" to "LKR",
    "NP" to "NPR",
    "CN" to "CNY",
    "HK" to "HKD",
    "TW" to "TWD",
    "JP" to "JPY",
    "KR" to "KRW",
    "SG" to "SGD",
    "MY" to "MYR",
    "TH" to "THB",
    "VN" to "VND",
    "ID" to "IDR",
    "PH" to "PHP",
    "KH" to "KHR",
    "AU" to "AUD",
    "NZ" to "NZD",
    "FJ" to "FJD",
)

private val PRICE_LEVEL: Map<String, Double> = mapOf(
    "US" to 1.05,
    "CA" to 1.35,
    "MX" to 0.35,
    "BR" to 0.3,
    "AR" to 0.2,
    "CL" to 0.35,
    "CO" to 0.2,
    "PE" to 0.22,
    "GB" to 1.3,
    "IE" to 1.1,
    "FR" to 0.95,
    "DE" to 1.0,
    "ES" to 0.7,
    "PT" to 0.7,
    "IT" to 0.7,
    "NL" to 1.2,
    "BE" to 0.9,
    "AT" to 1.05,
    "GR" to 0.5,
    "FI" to 0.75,
    "PL" to 0.45,
    "CZ" to 0.6,
    "HU" to 0.4,
    "RO" to 0.35,
    "BG" to 0.3,
    "RS" to 0.3,
    "UA" to 0.2,
    "RU" to 0.3,
    "TR" to 0.3,
    "CH" to 2.2,
    "NO" to 1.2,
    "SE" to 0.95,
    "DK" to 1.05,
    "IS" to 1.1,
    "AE" to 0.9,
    "SA" to 0.45,
    "QA" to 0.8,
    "KW" to 0.9,
    "IL" to 1.4,
    "EG" to 0.15,
    "MA" to 0.2,
    "ZA" to 0.2,
    "NG" to 0.15,
    "KE" to 0.15,
    "GH" to 0.12,
    "IN" to 0.18,
    "PK" to 0.1,
    "BD" to 0.12,
    "LK" to 0.12,
    "NP" to 0.12,
    "CN" to 0.9,
    "HK" to 3.2,
    "TW" to 1.1,
    "JP" to 0.85,
    "KR" to 1.2,
    "SG" to 2.6,
    "MY" to 0.25,
    "TH" to 0.3,
    "VN" to 0.25,
    "ID" to 0.2,
    "PH" to 0.2,
    "AU" to 1.5,
    "NZ" to 1.3,
)

private val GROSS_YIELD: Map<String, Double> = mapOf(
    "US" to 0.062,
    "CA" to 0.045,
    "GB" to 0.048,
    "DE" to 0.035,
    "FR" to 0.038,
    "ES" to 0.055,
    "IT" to 0.05,
    "CH" to 0.03,
    "JP" to 0.045,
    "KR" to 0.03,
    "CN" to 0.02,
    "HK" to 0.024,
    "SG" to 0.03,
    "TW" to 0.022,
    "AU" to 0.042,
    "NZ" to 0.038,
    "IN" to 0.03,
    "PK" to 0.045,
    "BR" to 0.06,
    "MX" to 0.07,
    "AR" to 0.055,
    "ZA" to 0.09,
    "NG" to 0.085,
    "KE" to 0.08,
    "EG" to 0.075,
    "TR" to 0.055,
    "RU" to 0.055,
    "UA" to 0.07,
    "PL" to 0.055,
    "TH" to 0.055,
    "VN" to 0.04,
    "ID" to 0.055,
    "PH" to 0.06,
    "MY" to 0.045,
    "AE" to 0.075,
)

private val IMPERIAL_AREA: Set<String> = setOf("US", "CA", "GB", "IN", "HK", "SG", "PK", "BD", "MY", "LK", "NP", "GH", "NG")

data class Market(val countryCode: String, val currency: String, val level: Double, val grossYield: Double, val imperial: Boolean)

private val DEFAULT_CURRENCY = "USD"
private const val DEFAULT_LEVEL = 0.5
private const val DEFAULT_YIELD = 0.06

fun marketFor(countryCode: String = ""): Market {
    val cc = countryCode.uppercase()
    return Market(
        countryCode = cc,
        currency = CURRENCIES[cc] ?: DEFAULT_CURRENCY,
        level = PRICE_LEVEL[cc] ?: DEFAULT_LEVEL,
        grossYield = GROSS_YIELD[cc] ?: DEFAULT_YIELD,
        imperial = IMPERIAL_AREA.contains(cc),
    )
}

// ponytail: simple currency-code prefix, not Intl.NumberFormat's locale-aware
// grouping/symbol. Good enough for a list price, not a receipt.
fun formatMoney(amount: Double, currency: String): String {
    val zeroDecimal = setOf("JPY", "KRW", "VND", "IDR", "CLP", "ISK", "HUF", "TWD")
    val rounded = if (currency in zeroDecimal) amount.toLong().toString() else amount.toLong().toString()
    return "$currency $rounded"
}

fun formatArea(sqft: Int, imperial: Boolean): String {
    val value = if (imperial) sqft else (sqft * 0.092903).toInt()
    val unit = if (imperial) "ft\u00b2" else "m\u00b2"
    return "$value $unit"
}
